# Generated by Django 3.0 on 2019-12-04 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0002_auto_20191204_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual'), ('weekly', 'Semanal')], default='monthly', max_length=10),
        ),
    ]
