# Generated by Django 3.0 on 2019-12-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_auto_20191205_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('daily', 'Diario'), ('monthly', 'Mensual')], default='monthly', max_length=10),
        ),
    ]
