# Generated by Django 3.0 on 2019-12-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20191212_0228'),
        ('newsletters', '0006_auto_20191205_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('daily', 'Diario')], default='monthly', max_length=10),
        ),
    ]
