# Generated by Django 3.0 on 2019-12-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0007_auto_20191212_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('daily', 'Diario'), ('weekly', 'Semanal')], default='monthly', max_length=10),
        ),
    ]
