# Generated by Django 3.0 on 2019-12-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_auto_20191219_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('weekly', 'Semanal'), ('daily', 'Diario')], default='monthly', max_length=10),
        ),
    ]
