# Generated by Django 3.0 on 2019-12-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0009_auto_20191219_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual'), ('weekly', 'Semanal')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
