# Generated by Django 3.0 on 2019-12-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0010_auto_20191219_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('daily', 'Diario'), ('monthly', 'Mensual')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
