# Generated by Django 3.0 on 2019-12-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0011_auto_20191219_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('daily', 'Diario')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
