# Generated by Django 3.0 on 2019-12-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20191212_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
    ]
